In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
%matplotlib inline

students = pd.read_csv('numpy_data.csv')
students.head()

ID (номер в журнале)  Рост, см  Масса тела, кг  Средний балл
0                     1       135              34           4.0
1                     2       160              43           5.0
2                     3       163              40           4.3
3                     4       147              44           5.0
4                     5       138              41           4.7

In [15]:
#Среднее арифметическое 

np.mean(students['Масса тела, кг'])

43.8

In [16]:
# Медиана

np.median(students['Масса тела, кг'])

42.0

In [17]:
# Cреднее средних

sort = np.sort(students['Средний балл'])
(sort[4]+sort[5])/2

4.449999999999999

In [18]:
#Коэффициент корреляции

corr = np.corrcoef(students['Рост, см'], students['Масса тела, кг'])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

In [23]:
# Математическое ожидание 


# Дисперсия
dispersia = np.var(students['Масса тела, кг'])
dispersia

60.36

In [19]:
# Стандартное отклонение 
std = np.std(students['Средний балл'])
std

0.4517742799230607

In [26]:
a = np.random.randint(1, 10, (10, 10))
np.max(a)

9

In [63]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

print((my_array[:,1:4])[1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
